### ISSUE TITLE
Idea : Dark Mode support

### ISSUE THREAD

**Issue by fynks** [Greenheart/pagecrypt#19]
Hello sir,
  I was using the original pagecrypt and just came across your version of pagecrypt and i must say it is worth using.Now i want to use it in my personal site but the only problem is lack of dark mode.So can you please add dark-mode to login page and all other area?

**Comment by Greenheart** [comment]
Happy to hear you enjoy the project so far! 😄

Feel free to create a pull request implementing this! The project is using Tailwind CSS for styling, [which makes it relatively simple to add dark mode designs](https://tailwindcss.com/docs/dark-mode).

The contribution instructions are not well documented at this time, but look at [these basic instructions](https://github.com/Greenheart/pagecrypt#development) and review the [npm scripts](https://github.com/Greenheart/pagecrypt/blob/main/package.json#L6-L13) used during development and you should be able to solve this.

Let me know if you have any questions!

**Comment by Greenheart** [comment]
@fynks Dark mode is added in version 5.2.0. Enjoy! :)

Also check out the new magic links to allow users to login with a single click: https://github.com/Greenheart/pagecrypt#share-a-magic-link-to-let-users-open-protected-pages-with-a-single-click
