### ISSUE TITLE
Autosubmit on focusout or add Submit button

### ISSUE THREAD

**Issue by amits97** [Greenheart/pagecrypt#29]
First of all, thank you for this really cool package!

I have a small suggestion: The UX is slightly confusing currently in mobile phones. Once I  enter the password, I usually hit "done" which closes the mobile keyboard - but doesn't submit the input. It would be really nice if you can submit the form on focusout of the input.

Better - add capability to customize the template

**Comment by Greenheart** [comment]
Hi Amit - glad to hear you enjoy the project!

Which mobile browser does this issue appear in?

I've investigated the latest Android Firefox (93.0) and Android Chrome (92.0) and both allow submitting the password by pressing "Done" / "Enter".

This might also be related to the on screen keyboard. I'm using https://github.com/AnySoftKeyboard/AnySoftKeyboard which handles this well, but maybe other keyboards don't provide the same functionality?

Ideally, I'd like to keep the design minimal and clean, but in the worst case we'll need to add a submit button.

**Comment by Greenheart** [comment]
To answer the second point about custom templates: It's something I've thought about but left for the future, since it would require larger changes to the package, while also adding complexity (increased maintenance cost).

Would be open to collaborate on PR:s implementing this feature if you're interested though.

**Comment by Greenheart** [comment]
@amits97 I just released `pagecrypt@5.3.0` that resolves this issue. Let me know if you run into any further issues.

Happy coding! :)

**Comment by amits97** [comment]
Hey, thank you so much for the quick update! I tried it out, works perfect now 😊👍
