### ISSUE TITLE
[Request]: Be able to specify the amount of rounds for encryption/decryption.

### ISSUE THREAD

**Issue by dillfrescott** [Greenheart/pagecrypt#38]
This way, one could have control over how secure against bruteforce attacks the generated page is!

**Comment by Greenheart** [comment]
I agree. This would make it possible to adjust the settings based on your threat model.

Feel free to create a PR implementing this, and I'll help get it ready for release :)

**Comment by dillfrescott** [comment]
I apologize I do not know how to implement this feature myself. Maybe someone will see this and add it though!

**Comment by Greenheart** [comment]
This is now implemented in pagecrypt@6.0.0 :smile:

https://www.npmjs.com/package/pagecrypt
