### ISSUE TITLE
Page not render after submit password form

### ISSUE THREAD

**Issue by taweewat-tk** [Greenheart/pagecrypt#41]
I have problem on static sites of rendar using react. It shows white page ...

I got two errors on console
```
GET https://test.onrender.com/%PUBLIC_URL%/manifest.json 400
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

Can you help me or Have another way?

Node version 16.19.0
script
"build": "react-scripts build && pagecrypt public/index.html build/index.html password",

**Comment by Greenheart** [comment]
Seems like this is related to your app and not pagecrypt.

The GET request to `https://test.onrender.com/%PUBLIC_URL%/manifest.json` resulted in HTTP 400 which means Bad Request. And looking at the URL, this makes sense, as `%PUBLIC_URL%` is something from your react app template.

Potential solution: Try replacing `%PUBLIC_URL%` with the actual path to where static assets are located in your built project.

Good luck and make a great day! :)


If you still think this is an issue with pagecrypt, you need to submit a minimal reproduction.
Learn more here: https://antfu.me/posts/why-reproductions-are-required
