### ISSUE TITLE
Add Automatic Decryption if password is given through URL Parameter

### ISSUE THREAD

**Issue by lukasbaumweb** [Greenheart/pagecrypt#48]
Maybe this sounds foolish but is it possible to decrypt the page automatically if the correct password is set in URL.

e.g. 

- https://example.com/?password=secret 
- https://example.com/encrypted.html?pw=s3cr3t

**Comment by Greenheart** [comment]
Hi Lukas! Yes, this is possible: https://github.com/Greenheart/pagecrypt#share-a-magic-link-to-let-users-open-protected-pages-with-a-single-click
