### ISSUE TITLE
Location Redirects

### ISSUE THREAD

**Issue by danielsherratt** [Greenheart/pagecrypt#52]
Hi, 

My HTML page simply redirects to another page, it uses location.replace("") and onload of body calls the function
![image](https://github.com/Greenheart/pagecrypt/assets/84758903/fe8d9dc4-7b0f-46ea-8bd4-bf65f9e8ee87)

However it appears the content is served in a iframe, is it possible to have it redirect instead?
![image](https://github.com/Greenheart/pagecrypt/assets/84758903/e72d4b8d-d1b2-4f6f-bd98-c01e2c17b6c7)

Daniel

**Comment by Greenheart** [comment]
Hi Daniel!

Which version of pagecrypt are you using? This project has not used an iframe since early 2021.

You might be using the original PageCrypt which was created by MaxLaumeister: https://github.com/MaxLaumeister/PageCrypt

Good luck! :)

**Comment by danielsherratt** [comment]
Thanks, I was using the old version, then ended up here to log a ticket🙃

**Comment by Greenheart** [comment]
No worries! Hope you can solve your problem :)
